# Generated by Django 5.2 on 2026-03-27 14:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=120)),
                ('aggregate_type', models.CharField(db_index=True, max_length=120)),
                ('aggregate_id', models.CharField(db_index=True, max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=160)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISPATCHED', 'Dispatched'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shared_domain_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='shared_doma_status_a4e153_idx'), models.Index(fields=['event_type', 'created_at'], name='shared_doma_event_t_c03426_idx')],
            },
        ),
    ]
