# Generated by Django 5.2 on 2026-03-30 20:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(db_index=True, max_length=120)),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('pdf', 'PDF'), ('docx', 'Word')], default='xlsx', max_length=16)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=20)),
                ('file_key', models.CharField(blank=True, default='', max_length=255)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_report_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shared_report_job',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='shared_repo_status_ba9262_idx'), models.Index(fields=['report_type', 'created_at'], name='shared_repo_report__345f7e_idx')],
            },
        ),
    ]
