# Generated by Django 5.2 on 2026-03-25 16:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('PDF', 'PDF'), ('TIFF', 'TIFF'), ('PRT', 'PRT'), ('Word', 'Word'), ('Excel', 'Excel'), ('Image', 'Image'), ('Other', 'Other')], default='PDF', max_length=20)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('In Review', 'In Review'), ('Approved', 'Approved'), ('Obsolete', 'Obsolete')], default='Draft', max_length=20)),
                ('file', models.FileField(upload_to='documents/')),
                ('size', models.BigIntegerField(default=0)),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('ocr_status', models.CharField(choices=[('Not Started', 'Not Started'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Not Started', max_length=20)),
                ('ocr_confidence', models.FloatField(default=0.0)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('linked_pl', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('revision', models.IntegerField(default=1)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('pl_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_cases', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edms_api.document')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.IntegerField()),
                ('file', models.FileField(upload_to='documents/versions/')),
                ('size', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_notes', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='edms_api.document')),
            ],
            options={
                'ordering': ['-revision'],
            },
        ),
        migrations.CreateModel(
            name='OcrJob',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_job', to='edms_api.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlItem',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='PL number must be exactly 8 digits.', regex='^\\d{8}$')])),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('UNDER_REVIEW', 'Under Review'), ('OBSOLETE', 'Obsolete')], default='ACTIVE', max_length=20)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('controlling_agency', models.CharField(blank=True, max_length=100, null=True)),
                ('safety_critical', models.BooleanField(default=False)),
                ('safety_classification', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20, null=True)),
                ('severity_of_failure', models.CharField(blank=True, max_length=255, null=True)),
                ('consequences', models.TextField(blank=True, null=True)),
                ('functionality', models.TextField(blank=True, null=True)),
                ('application_area', models.CharField(blank=True, max_length=255, null=True)),
                ('used_in', models.JSONField(blank=True, default=list)),
                ('drawing_numbers', models.JSONField(blank=True, default=list)),
                ('spec_numbers', models.JSONField(blank=True, default=list)),
                ('mother_part', models.CharField(blank=True, max_length=100, null=True)),
                ('uvam_item_id', models.CharField(blank=True, max_length=100, null=True)),
                ('str_number', models.CharField(blank=True, max_length=100, null=True)),
                ('eligibility_criteria', models.TextField(blank=True, null=True)),
                ('procurement_conditions', models.TextField(blank=True, null=True)),
                ('design_supervisor', models.CharField(blank=True, max_length=255, null=True)),
                ('concerned_supervisor', models.CharField(blank=True, max_length=255, null=True)),
                ('eoffice_file', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_type', models.CharField(blank=True, choices=[('VD', 'Vendor Directory'), ('NVD', 'Non-Vendor Directory')], max_length=10, null=True)),
                ('recent_activity', models.JSONField(blank=True, default=list)),
                ('engineering_changes', models.JSONField(blank=True, default=list)),
                ('linked_work_ids', models.JSONField(blank=True, default=list)),
                ('linked_case_ids', models.JSONField(blank=True, default=list)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status'], name='edms_api_pl_status_eb16d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlDocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_role', models.CharField(choices=[('GENERAL', 'General'), ('DRAWING', 'Drawing'), ('TECHNICAL_EVALUATION', 'Technical Evaluation'), ('ELIGIBILITY', 'Eligibility'), ('PROCUREMENT', 'Procurement'), ('SPECIFICATION', 'Specification'), ('CERTIFICATE', 'Certificate'), ('OTHER', 'Other')], default='GENERAL', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pl_links', to='edms_api.document')),
                ('pl_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='edms_api.plitem')),
            ],
            options={
                'ordering': ['-linked_at'],
            },
        ),
        migrations.CreateModel(
            name='PlBomLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('unit_of_measure', models.CharField(default='EA', max_length=20)),
                ('find_number', models.CharField(max_length=50)),
                ('line_order', models.PositiveIntegerField(default=0)),
                ('reference_designator', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_parents', to='edms_api.plitem')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_children', to='edms_api.plitem')),
            ],
            options={
                'ordering': ['line_order', 'find_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('work_category', models.CharField(choices=[('Maintenance', 'Maintenance'), ('Repair', 'Repair'), ('Inspection', 'Inspection'), ('Modification', 'Modification'), ('Testing', 'Testing')], max_length=50)),
                ('work_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('date', models.DateField()),
                ('pl_number', models.CharField(blank=True, max_length=100, null=True)),
                ('eoffice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('drawing_number', models.CharField(blank=True, max_length=100, null=True)),
                ('days_taken', models.IntegerField(default=0)),
                ('target_days', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_records', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_given', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_rejected', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status'], name='edms_api_ap_status_0ec259_idx'), models.Index(fields=['requested_by'], name='edms_api_ap_request_856411_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('DOWNLOAD', 'Download'), ('EXPORT', 'Export'), ('SEARCH', 'Search'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('OCR', 'OCR')], max_length=20)),
                ('module', models.CharField(choices=[('Document', 'Document'), ('WorkRecord', 'WorkRecord'), ('Case', 'Case'), ('User', 'User'), ('System', 'System'), ('OCR', 'OCR'), ('Approval', 'Approval')], max_length=50)),
                ('entity', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('Info', 'Info'), ('Warning', 'Warning'), ('Error', 'Error'), ('Critical', 'Critical')], default='Info', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action'], name='edms_api_au_action_45a827_idx'), models.Index(fields=['user'], name='edms_api_au_user_id_87ffa6_idx'), models.Index(fields=['module'], name='edms_api_au_module_8275ca_idx'), models.Index(fields=['severity'], name='edms_api_au_severit_d061ed_idx'), models.Index(fields=['created_at'], name='edms_api_au_created_bbbaab_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='edms_api_do_status_476bd6_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['author'], name='edms_api_do_author__e735e3_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['ocr_status'], name='edms_api_do_ocr_sta_ea7c31_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='edms_api_ca_status_1df8ed_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['severity'], name='edms_api_ca_severit_a83805_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['assigned_to'], name='edms_api_ca_assigne_9b27d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'revision')},
        ),
        migrations.AddIndex(
            model_name='ocrjob',
            index=models.Index(fields=['status'], name='edms_api_oc_status_55a351_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pldocumentlink',
            unique_together={('pl_item', 'document')},
        ),
        migrations.AlterUniqueTogether(
            name='plbomline',
            unique_together={('parent', 'find_number')},
        ),
        migrations.AddIndex(
            model_name='workrecord',
            index=models.Index(fields=['status'], name='edms_api_wo_status_2c7006_idx'),
        ),
        migrations.AddIndex(
            model_name='workrecord',
            index=models.Index(fields=['user_name'], name='edms_api_wo_user_na_064a93_idx'),
        ),
        migrations.AddIndex(
            model_name='workrecord',
            index=models.Index(fields=['date'], name='edms_api_wo_date_556a40_idx'),
        ),
    ]
