# Generated by Django 5.2 on 2026-03-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edms_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='closed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='closing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='concerned_officer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='consent_given',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='dispatch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='section_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='tender_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='user_section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='verification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('CLOSED', 'Closed'), ('Open', 'Open (Legacy)'), ('In Progress', 'In Progress (Legacy)'), ('Completed', 'Completed (Legacy)'), ('Closed', 'Closed (Legacy)')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='work_category',
            field=models.CharField(max_length=50),
        ),
    ]
