# Generated by Django 5.2 on 2026-03-30 08:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edms_api', '0003_supervisordocumentreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supervisordocumentreview',
            new_name='edms_api_su_status_c3a3e2_idx',
            old_name='suprev_status_idx',
        ),
        migrations.RenameIndex(
            model_name='supervisordocumentreview',
            new_name='edms_api_su_pl_item_2cd879_idx',
            old_name='suprev_pl_status_idx',
        ),
        migrations.RenameIndex(
            model_name='supervisordocumentreview',
            new_name='edms_api_su_latest__0601b7_idx',
            old_name='suprev_doc_status_idx',
        ),
        migrations.AddField(
            model_name='document',
            name='search_indexed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='search_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='document',
            name='search_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('DOWNLOAD', 'Download'), ('EXPORT', 'Export'), ('SEARCH', 'Search'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('APPROVE', 'Approve'), ('BYPASS', 'Bypass'), ('REJECT', 'Reject'), ('REVIEW', 'Review'), ('OCR', 'OCR')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['search_indexed_at'], name='edms_api_do_search__9deb3b_idx'),
        ),
    ]
