# Generated by Django 5.2 on 2026-03-30 09:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edms_api', '0004_rename_suprev_status_idx_edms_api_su_status_c3a3e2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='duplicate_group_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='duplicate_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_children', to='edms_api.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='duplicate_status',
            field=models.CharField(choices=[('UNIQUE', 'Unique'), ('MASTER', 'Master'), ('DUPLICATE', 'Duplicate')], default='UNIQUE', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='external_file_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='fingerprint_3x64k',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='hash_algo',
            field=models.CharField(default='sha256', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='hash_indexed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='hash_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='document',
            name='source_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='source_modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='source_system',
            field=models.CharField(choices=[('UPLOAD', 'Upload'), ('FILE_SHARE', 'File Share'), ('NETWORK_SHARE', 'Network Share'), ('SCANNER', 'Scanner'), ('EMAIL', 'Email'), ('IMPORT', 'Import')], default='UPLOAD', max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentContentIndex',
            fields=[
                ('content_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size_bytes', models.BigIntegerField()),
                ('fingerprint_3x64k', models.CharField(max_length=64)),
                ('full_hash_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('hash_algo', models.CharField(default='sha256', max_length=50)),
                ('hash_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['size_bytes', 'fingerprint_3x64k'], name='edms_api_do_size_by_3d3bfe_idx'), models.Index(fields=['full_hash_sha256'], name='edms_api_do_full_ha_541fa5_idx')],
                'unique_together': {('size_bytes', 'fingerprint_3x64k', 'hash_version')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='content_index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='edms_api.documentcontentindex'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['source_system'], name='edms_api_do_source__987e1d_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['duplicate_status'], name='edms_api_do_duplica_e8d7cb_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['duplicate_group_key'], name='edms_api_do_duplica_4457c9_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['size', 'fingerprint_3x64k'], name='edms_api_do_size_aabd62_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_hash'], name='edms_api_do_file_ha_e54f4c_idx'),
        ),
    ]
