# Generated by Django 5.2 on 2026-03-30 13:55

import django.db.models.deletion
import django_fsm
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edms_api', '0005_document_duplicate_group_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(choices=[('Document', 'Document'), ('WorkRecord', 'WorkRecord'), ('Case', 'Case'), ('User', 'User'), ('System', 'System'), ('OCR', 'OCR'), ('Approval', 'Approval'), ('ConfigMgmt', 'ConfigMgmt')], max_length=50),
        ),
        migrations.CreateModel(
            name='Baseline',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('baseline_number', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('status', django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('RELEASED', 'Released'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=50, protected=True)),
                ('impact_preview', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_baselines', to=settings.AUTH_USER_MODEL)),
                ('pl_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='edms_api.plitem')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_baselines', to=settings.AUTH_USER_MODEL)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='edms_api.baseline')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='plitem',
            name='current_released_baseline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_for_pl_items', to='edms_api.baseline'),
        ),
        migrations.CreateModel(
            name='ChangeNotice',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('notice_number', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('effectivity_date', models.DateField(blank=True, null=True)),
                ('status', django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('APPROVED', 'Approved'), ('RELEASED', 'Released'), ('CLOSED', 'Closed')], default='DRAFT', max_length=50, protected=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_change_notices', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_change_notices', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_change_notices', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_change_notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='baseline',
            name='source_change_notice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baselines', to='edms_api.changenotice'),
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('impact_summary', models.TextField(blank=True, null=True)),
                ('status', django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IMPLEMENTED', 'Implemented')], default='DRAFT', max_length=50, protected=True)),
                ('release_notes', models.TextField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pl_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='edms_api.plitem')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_change_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_change_requests', to=settings.AUTH_USER_MODEL)),
                ('source_baseline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_change_requests', to='edms_api.baseline')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddField(
            model_name='changenotice',
            name='change_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_notices', to='edms_api.changerequest'),
        ),
        migrations.AddField(
            model_name='baseline',
            name='source_change_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baselines', to='edms_api.changerequest'),
        ),
        migrations.CreateModel(
            name='BaselineItem',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('BOM_LINE', 'BOM Line'), ('DOCUMENT', 'Document')], max_length=20)),
                ('source_object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('document_revision', models.IntegerField(blank=True, null=True)),
                ('document_status', models.CharField(blank=True, max_length=20, null=True)),
                ('link_role', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=20, null=True)),
                ('find_number', models.CharField(blank=True, max_length=50, null=True)),
                ('line_order', models.PositiveIntegerField(default=0)),
                ('reference_designator', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('snapshot_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='edms_api.baseline')),
                ('child_pl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseline_child_items', to='edms_api.plitem')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseline_items', to='edms_api.document')),
                ('parent_pl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseline_parent_items', to='edms_api.plitem')),
            ],
            options={
                'ordering': ['line_order', 'created_at', 'id'],
                'indexes': [models.Index(fields=['baseline', 'item_type'], name='edms_api_ba_baselin_9520b4_idx'), models.Index(fields=['baseline', 'line_order'], name='edms_api_ba_baselin_899077_idx'), models.Index(fields=['document', 'item_type'], name='edms_api_ba_documen_551246_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='changerequest',
            index=models.Index(fields=['pl_item', 'status'], name='edms_api_ch_pl_item_411b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='changerequest',
            index=models.Index(fields=['status', 'requested_at'], name='edms_api_ch_status_db0bd4_idx'),
        ),
        migrations.AddIndex(
            model_name='changenotice',
            index=models.Index(fields=['change_request', 'status'], name='edms_api_ch_change__63ea1f_idx'),
        ),
        migrations.AddIndex(
            model_name='changenotice',
            index=models.Index(fields=['status', 'created_at'], name='edms_api_ch_status_ad7139_idx'),
        ),
        migrations.AddIndex(
            model_name='baseline',
            index=models.Index(fields=['pl_item', 'status'], name='edms_api_ba_pl_item_a4568a_idx'),
        ),
        migrations.AddIndex(
            model_name='baseline',
            index=models.Index(fields=['status', 'created_at'], name='edms_api_ba_status_ef476e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='baseline',
            unique_together={('pl_item', 'baseline_number')},
        ),
    ]
