# Generated by Django 5.2 on 2026-03-30 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edms_api', '0006_alter_auditlog_module_baseline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['source_system', 'duplicate_status'], name='edms_api_do_source__c08d77_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['category'], name='edms_api_do_categor_407812_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['linked_pl'], name='edms_api_do_linked__d9f8e4_idx'),
        ),
    ]
