# Generated by Django 5.2 on 2026-03-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edms_api', '0007_document_edms_api_do_source__c08d77_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baselineitem',
            name='item_type',
            field=models.CharField(choices=[('PL_ITEM', 'PL Item'), ('BOM_LINE', 'BOM Line'), ('DOCUMENT', 'Document')], max_length=20),
        ),
    ]
