# Generated by Django 5.2 on 2026-03-31 04:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edms_api', '0008_alter_baselineitem_item_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_family_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_family_key'], name='edms_api_do_documen_9ca811_idx'),
        ),
    ]
