# Generated by Django 5.2 on 2026-03-30 13:57

import django.db.models.deletion
import django_fsm
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edms_api', '0007_document_edms_api_do_source__c08d77_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexedSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('source_system', models.CharField(default='NETWORK_SHARE', max_length=30)),
                ('root_path', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('watch_enabled', models.BooleanField(default=True)),
                ('include_extensions', models.JSONField(blank=True, default=list)),
                ('exclude_patterns', models.JSONField(blank=True, default=list)),
                ('scan_interval_minutes', models.PositiveIntegerField(default=60)),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_crawl_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HashBackfillJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', django_fsm.FSMField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=50, protected=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_size', models.PositiveIntegerField(default=500)),
                ('documents_scanned', models.PositiveIntegerField(default=0)),
                ('documents_indexed', models.PositiveIntegerField(default=0)),
                ('full_hashes_computed', models.PositiveIntegerField(default=0)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_jobs', to='documents.indexedsource')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', django_fsm.FSMField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=50, protected=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discovered_count', models.PositiveIntegerField(default=0)),
                ('indexed_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_jobs', to='documents.indexedsource')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DuplicateDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_key', models.CharField(db_index=True, max_length=255)),
                ('decision', models.CharField(choices=[('MERGE', 'Merge'), ('IGNORE', 'Ignore')], max_length=32)),
                ('status', django_fsm.FSMField(default='OPEN', max_length=50, protected=True)),
                ('candidate_documents', models.JSONField(blank=True, default=list)),
                ('candidate_count', models.PositiveIntegerField(default=0)),
                ('storage_saved_bytes', models.BigIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('source_system', models.CharField(blank=True, default='', max_length=30)),
                ('document_class', models.CharField(blank=True, default='', max_length=100)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('master_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_duplicate_decisions', to='edms_api.document')),
            ],
            options={
                'ordering': ['-decided_at'],
                'indexes': [models.Index(fields=['group_key', 'status'], name='documents_d_group_k_fc77fd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='indexedsource',
            index=models.Index(fields=['is_active', 'source_system'], name='documents_i_is_acti_9b6743_idx'),
        ),
        migrations.AddIndex(
            model_name='indexedsource',
            index=models.Index(fields=['watch_enabled', 'scan_interval_minutes'], name='documents_i_watch_e_efce90_idx'),
        ),
        migrations.AddIndex(
            model_name='hashbackfilljob',
            index=models.Index(fields=['status', 'created_at'], name='documents_h_status_01b81e_idx'),
        ),
        migrations.AddIndex(
            model_name='hashbackfilljob',
            index=models.Index(fields=['source', 'status'], name='documents_h_source__c595d7_idx'),
        ),
        migrations.AddIndex(
            model_name='crawljob',
            index=models.Index(fields=['status', 'created_at'], name='documents_c_status_1a3d4e_idx'),
        ),
        migrations.AddIndex(
            model_name='crawljob',
            index=models.Index(fields=['source', 'status'], name='documents_c_source__9d5a19_idx'),
        ),
    ]
