# Generated by Django 5.2 on 2026-03-30 14:06

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicatedecision',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplicatedecision',
            name='status',
            field=django_fsm.FSMField(choices=[('PENDING', 'Pending'), ('APPLIED', 'Applied'), ('IGNORED', 'Ignored')], default='PENDING', max_length=50, protected=True),
        ),
    ]
