# Generated by Django 5.2 on 2026-03-31 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_duplicatedecision_decided_at_and_more'),
        ('edms_api', '0008_alter_baselineitem_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentOcrEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=60)),
                ('entity_value', models.CharField(max_length=255)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('source_engine', models.CharField(blank=True, default='', max_length=50)),
                ('source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_entities', to='edms_api.document')),
            ],
            options={
                'ordering': ['entity_type', 'entity_value'],
                'indexes': [models.Index(fields=['document', 'entity_type'], name='documents_d_documen_ba0eb7_idx'), models.Index(fields=['entity_type', 'entity_value'], name='documents_d_entity__a811bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentOcrPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('source_engine', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_pages', to='edms_api.document')),
            ],
            options={
                'ordering': ['page_number'],
                'indexes': [models.Index(fields=['document', 'page_number'], name='documents_d_documen_f2e704_idx')],
                'unique_together': {('document', 'page_number')},
            },
        ),
    ]
