# Generated by Django 5.2 on 2026-03-31 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentocrentity_documentocrpage'),
        ('edms_api', '0009_document_document_family_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexedSourceFileState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_path', models.TextField()),
                ('absolute_path', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MISSING', 'Missing'), ('FAILED', 'Failed')], default='ACTIVE', max_length=20)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('source_modified_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indexed_source_states', to='edms_api.document')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_states', to='documents.indexedsource')),
            ],
            options={
                'ordering': ['relative_path'],
                'indexes': [models.Index(fields=['source', 'status'], name='documents_i_source__3b2bdb_idx'), models.Index(fields=['source', 'last_seen_at'], name='documents_i_source__f8b889_idx'), models.Index(fields=['document'], name='documents_i_documen_58d2dd_idx')],
                'unique_together': {('source', 'relative_path')},
            },
        ),
    ]
