# Generated by Django 5.2 on 2026-03-31 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_indexedsourcefilestate'),
        ('edms_api', '0009_document_document_family_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMetadataAssertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=80)),
                ('value', models.CharField(max_length=255)),
                ('normalized_value', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(choices=[('machine', 'Machine'), ('manual', 'Manual'), ('workflow', 'Workflow')], default='machine', max_length=20)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUPERSEDED', 'Superseded')], default='PROPOSED', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['field_key', '-updated_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='documentocrentity',
            name='documents_d_entity__a811bb_idx',
        ),
        migrations.AddField(
            model_name='documentocrentity',
            name='method',
            field=models.CharField(blank=True, default='ocr_regex', max_length=30),
        ),
        migrations.AddField(
            model_name='documentocrentity',
            name='normalized_value',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='documentocrentity',
            name='review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='documentocrentity',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('OVERRIDDEN', 'Overridden')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='documentocrentity',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentocrentity',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ocr_entities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentocrentity',
            name='source_span',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='documentocrentity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='documentocrentity',
            index=models.Index(fields=['document', 'review_status'], name='documents_d_documen_831194_idx'),
        ),
        migrations.AddIndex(
            model_name='documentocrentity',
            index=models.Index(fields=['entity_type', 'normalized_value'], name='documents_d_entity__ebbd1d_idx'),
        ),
        migrations.AddField(
            model_name='documentmetadataassertion',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_metadata_assertions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentmetadataassertion',
            name='derived_from_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_assertions', to='documents.documentocrentity'),
        ),
        migrations.AddField(
            model_name='documentmetadataassertion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_assertions', to='edms_api.document'),
        ),
        migrations.AddField(
            model_name='documentmetadataassertion',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_metadata_assertions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='documentmetadataassertion',
            index=models.Index(fields=['document', 'status'], name='documents_d_documen_eb8f3f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentmetadataassertion',
            index=models.Index(fields=['field_key', 'normalized_value'], name='documents_d_field_k_5ab4b6_idx'),
        ),
    ]
